basePath: /api
host: localhost:5000
info:
  contact: {}
  description: This is a sample swagger doc for test
  title: Swagger Example API
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: get user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get user example
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
