info:
  contact: {}
paths:
  /user:
    get:
      consumes:
      - application/json
      description: get user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: get user example
      tags:
      - example
swagger: "2.0"
